# golangci-lint configuration file
version: "2"

run:
  timeout: 5m

output:
  format: colored-line-number

linters-settings:
  govet:
    check-shadowing: true
  errcheck:
    check-type-assertions: true
  cyclop:
    max-complexity: 15

linters:
  disable:
    - contextcheck
    - exhaustruct
    - errcheck
  enable:
    - govet
    - bodyclose
    - dupl
    - gocritic
    - gocyclo